"""
signal_agent/signal_engine.py
Core Signal Agent — scans all markets and generates trade signals.
"""
from __future__ import annotations

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
import pandas as pd

from chart_agent.ta_analysis import run_full_analysis
from data_feeds import crypto, stocks, forex, commodities
from signal_agent.conditions import (
    check_trend_filter,
    check_momentum,
    check_volume_confirmation,
)


# ── Watchlist ─────────────────────────────────────────────────────────────────

WATCHLIST: Dict[str, List[str]] = {
    "crypto":      ["bitcoin", "ethereum", "solana", "cardano", "binancecoin", "ripple"],
    "stocks":      ["SPY", "TSLA"],
    "forex":       [
        "EUR_USD", "GBP_USD",
        "GBP_JPY", "USD_JPY", "AUD_USD", "USD_CAD", "EUR_GBP", "EUR_JPY", "NZD_USD",
    ],
    "commodities": ["WTI", "WHEAT", "GLD", "SLV"],
}

# Default OHLCV fetch params per market
_OHLCV_PARAMS: Dict[str, Dict[str, Any]] = {
    "crypto":      {"days": 30},
    "stocks":      {"timeframe": "1Day", "limit": 60},
    "forex":       {"granularity": "H4", "count": 300},
    "commodities": {"outputsize": "compact"},
}

# Display symbol override (CoinGecko IDs / feed keys -> tickers)
_DISPLAY_SYMBOL: Dict[str, str] = {
    "bitcoin":     "BTC",
    "ethereum":    "ETH",
    "solana":      "SOL",
    "cardano":     "ADA",
    "binancecoin": "BNB",
    "ripple":      "XRP",
    "GLD":         "XAUUSD",  # Gold ETF proxy
    "SLV":         "XAGUSD",  # Silver ETF proxy
}

# Minimum candles required before analysis is meaningful
_MIN_CANDLES = 20

# Minimum confluence score to emit a signal
_MIN_CONFLUENCE = 5

# Minimum risk-reward ratio to emit a signal
_MIN_RR = 2.5


# ── Signal dataclass ──────────────────────────────────────────────────────────

@dataclass
class Signal:
    """
    A trade signal generated by the signal engine.

    Fields
    ------
    asset           : canonical display ticker (e.g. 'BTC', 'EUR_USD')
    market          : 'crypto' | 'stocks' | 'forex' | 'commodities'
    direction       : 'LONG' | 'SHORT'
    entry_low       : lower bound of the entry zone
    entry_high      : upper bound of the entry zone
    target          : profit target price
    stop_loss       : stop-loss price
    risk_reward     : ratio of reward to risk (target distance / stop distance)
    confidence      : 0-100 integer score
    confluence_score: 0-6 raw TA confluence count
    conditions_met  : list of TA conditions that fired
    reasoning       : short human-readable summary
    timestamp       : UTC ISO-8601 string
    """
    asset:            str
    market:           str
    direction:        str
    entry_low:        float
    entry_high:       float
    target:           float
    stop_loss:        float
    risk_reward:      float
    confidence:       int
    confluence_score: int
    conditions_met:   List[str]
    reasoning:        str
    timestamp:        str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "asset":            self.asset,
            "market":           self.market,
            "direction":        self.direction,
            "entry_low":        self.entry_low,
            "entry_high":       self.entry_high,
            "target":           self.target,
            "stop_loss":        self.stop_loss,
            "risk_reward":      self.risk_reward,
            "confidence":       self.confidence,
            "confluence_score": self.confluence_score,
            "conditions_met":   self.conditions_met,
            "reasoning":        self.reasoning,
            "timestamp":        self.timestamp,
        }


# ── OHLCV -> DataFrame ────────────────────────────────────────────────────────

def build_dataframe(ohlcv_data: List[Dict[str, Any]], market: str) -> pd.DataFrame:
    """
    Convert raw OHLCV records from any feed into a clean DataFrame.

    Each feed returns slightly different key names:
      crypto      : timestamp_ms, open, high, low, close, volume
      stocks      : timestamp, open, high, low, close, volume
      forex       : timestamp, open, high, low, close, volume
      commodities : date, open, high, low, close, volume

    Normalises all to lowercase OHLCV columns, converts to float,
    drops NaN rows, and resets the index.

    Args:
        ohlcv_data : list of dicts from any feed's get_ohlcv()
        market     : 'crypto' | 'stocks' | 'forex' | 'commodities'

    Returns:
        Clean DataFrame with columns: open, high, low, close, volume
        Returns empty DataFrame on error.
    """
    if not ohlcv_data:
        return pd.DataFrame()

    try:
        df = pd.DataFrame(ohlcv_data)
        df.columns = df.columns.str.lower()

        for col in ("open", "high", "low", "close"):
            if col not in df.columns:
                print(f"[signal] build_dataframe: missing column '{col}' for {market}")
                return pd.DataFrame()

        if "volume" not in df.columns:
            df["volume"] = 0.0

        df = df[["open", "high", "low", "close", "volume"]].apply(
            pd.to_numeric, errors="coerce"
        )
        df = df.dropna(subset=["open", "high", "low", "close"]).reset_index(drop=True)
        return df

    except Exception as e:
        print(f"[signal] build_dataframe error ({market}): {e}")
        return pd.DataFrame()


# ── Swing-Based Stop Helper ───────────────────────────────────────────────────

def _find_swing_stop(df: pd.DataFrame, direction: str) -> Optional[float]:
    """
    Locate the most recent opposing swing point across the last 3 swings and
    place the stop 0.1% beyond it.

    LONG  : stop 0.1% below the most recent swing low.
    SHORT : stop 0.1% above the most recent swing high.

    Returns None when there are too few candles for swing detection.
    """
    order = 3
    n     = len(df)

    if direction == "LONG":
        lows: List[float] = []
        for i in range(order, n - order):
            window = df["low"].iloc[i - order: i + order + 1]
            if float(df["low"].iloc[i]) == float(window.min()):
                lows.append(float(df["low"].iloc[i]))
        if lows:
            recent = lows[-3:]
            return round(recent[-1] * 0.999, 6)  # 0.1% below most recent swing low

    else:  # SHORT
        highs: List[float] = []
        for i in range(order, n - order):
            window = df["high"].iloc[i - order: i + order + 1]
            if float(df["high"].iloc[i]) == float(window.max()):
                highs.append(float(df["high"].iloc[i]))
        if highs:
            recent = highs[-3:]
            return round(recent[-1] * 1.001, 6)  # 0.1% above most recent swing high

    return None


# ── Entry Zone Structure Validation ───────────────────────────────────────────

def _validate_entry_near_structure(
    entry_low: float,
    entry_high: float,
    analysis: Dict[str, Any],
) -> bool:
    """
    Return True only if the entry zone midpoint is within 0.3% of at least
    one structural level: support, resistance, or a supply/demand zone edge.

    Signals whose entry floats in open space with no nearby structure are
    rejected to avoid low-probability entries.
    """
    entry_mid = (entry_low + entry_high) / 2.0
    threshold = 0.003  # 0.3%

    kl  = analysis.get("key_levels", {})
    sdz = analysis.get("supply_demand_zones", {})

    all_levels: List[float] = (
        list(kl.get("support", [])) + list(kl.get("resistance", []))
    )
    for zone in sdz.get("demand_zones", []) + sdz.get("supply_zones", []):
        all_levels.append(zone["top"])
        all_levels.append(zone["bottom"])

    for level in all_levels:
        if level and abs(entry_mid - level) / max(abs(entry_mid), 1e-9) <= threshold:
            return True
    return False


# ── Entry / Target / Stop ─────────────────────────────────────────────────────

def calculate_entry_target_stop(
    analysis: Dict[str, Any],
    direction: str,
    current_price: float,
    df: Optional[pd.DataFrame] = None,
) -> Tuple[float, float, float, float, float]:
    """
    Derive entry zone (low, high), profit target, stop-loss, and R:R ratio
    from TA results.

    Priority order for each level:
      Entry zone  -- nearest supply/demand zone edge, or key level, or 0.2% band
      Target      -- next key level beyond entry, or nearest Fib level
      Stop        -- beyond nearest swing point (0.1% past last swing in opposing
                     direction); falls back to structure-based stop when no swing
                     is detectable

    Args:
        analysis      : dict returned by run_full_analysis()
        direction     : 'LONG' | 'SHORT'
        current_price : float
        df            : optional OHLCV DataFrame used for swing-based stop

    Returns:
        (entry_low, entry_high, target, stop_loss, risk_reward)
    """
    kl  = analysis.get("key_levels", {})
    fib = analysis.get("fibonacci", {})
    sdz = analysis.get("supply_demand_zones", {})

    supports      = kl.get("support", [])
    resistances   = kl.get("resistance", [])
    fib_levels    = list(fib.get("levels", {}).values()) if "levels" in fib else []
    demand_zones  = sdz.get("demand_zones", [])
    supply_zones  = sdz.get("supply_zones", [])

    price = current_price

    if direction == "LONG":
        # Entry zone
        if demand_zones:
            entry_low  = demand_zones[0]["bottom"]
            entry_high = demand_zones[0]["top"]
        elif supports:
            entry_low  = round(supports[0] * 0.998, 6)
            entry_high = round(supports[0] * 1.002, 6)
        else:
            entry_low  = round(price * 0.998, 6)
            entry_high = round(price * 1.002, 6)

        # Target
        target_cands = [r for r in resistances if r > entry_high]
        fib_targets  = [f for f in fib_levels if f and f > entry_high]
        if target_cands:
            target = target_cands[0]
        elif fib_targets:
            target = min(fib_targets)
        else:
            target = round(entry_high * 1.02, 6)

        # Stop: swing-based first, then fall back to structure
        swing_stop = _find_swing_stop(df, "LONG") if df is not None else None
        if swing_stop is not None:
            stop_loss = swing_stop
        elif demand_zones:
            stop_loss = round(demand_zones[0]["bottom"] * 0.998, 6)
        elif len(supports) > 1:
            stop_loss = round(supports[1] * 0.998, 6)
        elif supports:
            stop_loss = round(supports[0] * 0.996, 6)
        else:
            stop_loss = round(price * 0.98, 6)

    else:  # SHORT
        # Entry zone
        if supply_zones:
            entry_low  = supply_zones[0]["bottom"]
            entry_high = supply_zones[0]["top"]
        elif resistances:
            entry_low  = round(resistances[0] * 0.998, 6)
            entry_high = round(resistances[0] * 1.002, 6)
        else:
            entry_low  = round(price * 0.998, 6)
            entry_high = round(price * 1.002, 6)

        # Target
        target_cands = [s for s in supports if s < entry_low]
        fib_targets  = [f for f in fib_levels if f and f < entry_low]
        if target_cands:
            target = target_cands[0]
        elif fib_targets:
            target = max(fib_targets)
        else:
            target = round(entry_low * 0.98, 6)

        # Stop: swing-based first, then fall back to structure
        swing_stop = _find_swing_stop(df, "SHORT") if df is not None else None
        if swing_stop is not None:
            stop_loss = swing_stop
        elif supply_zones:
            stop_loss = round(supply_zones[0]["top"] * 1.002, 6)
        elif len(resistances) > 1:
            stop_loss = round(resistances[1] * 1.002, 6)
        elif resistances:
            stop_loss = round(resistances[0] * 1.004, 6)
        else:
            stop_loss = round(price * 1.02, 6)

    # Safety guard: stop must always be on the correct side of the entry zone.
    # A swing lookup can return a level that is on the wrong side when the most
    # recent swing is inside the entry zone or below/above it.
    if direction == "LONG" and stop_loss >= entry_low:
        stop_loss = round(entry_low * 0.99, 6)
    elif direction == "SHORT" and stop_loss <= entry_high:
        stop_loss = round(entry_high * 1.01, 6)

    entry_mid   = (entry_low + entry_high) / 2
    risk        = abs(entry_mid - stop_loss)
    reward      = abs(target - entry_mid)
    risk_reward = round(reward / risk, 2) if risk > 0 else 0.0

    return (
        round(entry_low,  6),
        round(entry_high, 6),
        round(target,     6),
        round(stop_loss,  6),
        risk_reward,
    )


# ── Signal Scoring ────────────────────────────────────────────────────────────

def score_signal(
    analysis: Dict[str, Any],
    direction: str,
) -> Tuple[int, List[str]]:
    """
    Convert TA analysis results into a confidence score 0-100 and a list
    of conditions met.

    Scoring breakdown (max 100):
      Confluence score  : up to 30 pts  (5 pts per confluence point)
      Trend alignment   : 20 pts
      Price action match: 15 pts
      Volume confirm    : 15 pts
      Key level touch   : 10 pts
      Volume penalty    : -10 pts if diverging

    Args:
        analysis  : dict from run_full_analysis()
        direction : 'LONG' | 'SHORT'

    Returns:
        (confidence 0-100, list_of_conditions_met)
    """
    score = 0
    conditions: List[str] = []

    # 1. Raw confluence (5 pts each, max 30)
    confluence = analysis.get("confluence_score", 0)
    conf_pts   = min(30, confluence * 5)
    score     += conf_pts
    if confluence > 0:
        conditions.append(f"Confluence {confluence}/6 (+{conf_pts}pts)")

    # 2. Trend alignment (20 pts)
    trend         = analysis.get("market_structure", {}).get("trend", "RANGING")
    trend_aligned = (
        (direction == "LONG"  and trend == "BULLISH") or
        (direction == "SHORT" and trend == "BEARISH")
    )
    if trend_aligned:
        score += 20
        conditions.append(f"Trend aligned: {trend} -> {direction} (+20pts)")
    elif trend == "RANGING":
        conditions.append("Trend: RANGING (no trend bonus)")
    else:
        conditions.append(f"Counter-trend: {trend} vs {direction} (no trend bonus)")

    # 3. Price action match (15 pts)
    patterns         = analysis.get("price_action", {}).get("patterns", [])
    bullish_patterns = {"bullish_engulfing", "pin_bar_bullish", "liquidity_sweep_low"}
    bearish_patterns = {"bearish_engulfing", "pin_bar_bearish", "liquidity_sweep_high"}

    if direction == "LONG":
        matched = [p for p in patterns if p in bullish_patterns]
    else:
        matched = [p for p in patterns if p in bearish_patterns]

    if matched:
        score += 15
        conditions.append(f"PA confirms {direction}: {', '.join(matched)} (+15pts)")
    elif patterns:
        conditions.append(f"PA present but not directional: {patterns}")

    # 4. Volume confirmation (15 pts / -10 penalty)
    vol_signal = analysis.get("volume", {}).get("signal", "WEAK")
    if vol_signal == "CONFIRMING":
        score += 15
        conditions.append("Volume confirming move (+15pts)")
    elif vol_signal == "DIVERGING":
        score -= 10
        conditions.append("Volume diverging -- penalty (-10pts)")
    else:
        conditions.append("Volume weak -- no bonus")

    # 5. Key level touch (10 pts)
    kl    = analysis.get("key_levels", {})
    price = kl.get("current_price", 0)
    sups  = kl.get("support", [])
    ress  = kl.get("resistance", [])

    near_sup = sups and abs(price - sups[0]) / max(price, 1e-9) < 0.008
    near_res = ress and abs(price - ress[0]) / max(price, 1e-9) < 0.008

    if (direction == "LONG" and near_sup) or (direction == "SHORT" and near_res):
        score += 10
        lvl_type = "support" if direction == "LONG" else "resistance"
        conditions.append(f"Price at key {lvl_type} (+10pts)")

    return max(0, min(100, score)), conditions


# ── Core Signal Generator ─────────────────────────────────────────────────────

def generate_signal(symbol: str, market: str) -> Optional[Signal]:
    """
    Fetch OHLCV data, run full TA analysis, score the result, and return a
    Signal if the setup is strong enough (confluence >= _MIN_CONFLUENCE).

    Args:
        symbol : asset identifier for the relevant feed
        market : 'crypto' | 'stocks' | 'forex' | 'commodities'

    Returns:
        Signal object, or None if setup is too weak or data unavailable.
    """
    display = _DISPLAY_SYMBOL.get(symbol, symbol)

    # Fetch OHLCV
    try:
        params = _OHLCV_PARAMS.get(market, {})
        if market == "crypto":
            ohlcv = crypto.get_ohlcv(symbol, **params)
        elif market == "stocks":
            ohlcv = stocks.get_ohlcv(symbol, **params)
        elif market == "forex":
            ohlcv = forex.get_ohlcv(symbol, **params)
        elif market == "commodities":
            ohlcv = commodities.get_ohlcv(symbol, **params)
        else:
            print(f"[signal] Unknown market: {market}")
            return None
    except Exception as e:
        print(f"[signal] OHLCV fetch failed for {display} ({market}): {e}")
        return None

    if not ohlcv:
        print(f"[signal] No OHLCV data for {display} ({market})")
        return None

    # Build DataFrame
    df = build_dataframe(ohlcv, market)
    if df.empty or len(df) < _MIN_CANDLES:
        print(f"[signal] Insufficient candles for {display} ({market}): {len(df)}")
        return None

    # Run TA
    try:
        timeframe_map = {
            "crypto": "Daily", "stocks": "Daily",
            "forex": "H4",     "commodities": "Monthly",
        }
        analysis = run_full_analysis(df, symbol=display, timeframe=timeframe_map[market])
    except Exception as e:
        print(f"[signal] TA failed for {display} ({market}): {e}")
        return None

    # Apply HTF agreement penalty before initial confluence check
    confluence    = analysis.get("confluence_score", 0)
    htf_agreement = analysis.get("htf_agreement", True)
    if not htf_agreement:
        confluence = max(0, confluence - 2)
        print(f"[signal] {display}: HTF disagreement — confluence reduced to {confluence}")

    if confluence < _MIN_CONFLUENCE:
        print(f"[signal] {display} ({market}): confluence {confluence} < {_MIN_CONFLUENCE} -- skipping")
        return None

    # Determine direction
    bias = analysis.get("bias", "NEUTRAL")
    if bias in ("BULLISH", "CAUTIOUSLY_BULLISH"):
        direction = "LONG"
        confidence, conditions = score_signal(analysis, direction)
    elif bias in ("BEARISH", "CAUTIOUSLY_BEARISH"):
        direction = "SHORT"
        confidence, conditions = score_signal(analysis, direction)
    else:
        # NEUTRAL -- pick the stronger side
        long_score,  long_conds  = score_signal(analysis, "LONG")
        short_score, short_conds = score_signal(analysis, "SHORT")
        if long_score >= short_score:
            direction, confidence, conditions = "LONG",  long_score,  long_conds
        else:
            direction, confidence, conditions = "SHORT", short_score, short_conds

    # -- Trend filter: hard block if trading against EMA50/200 --
    trend_passed, trend_score, trend_reason = check_trend_filter(df, direction)
    if not trend_passed:
        print(f"[signal] {display}: {trend_reason} -- skipping")
        return None
    confidence = min(100, confidence + trend_score)
    conditions.append(trend_reason)

    # -- Volume confirmation: hard reject if < 50% of 20-period avg --
    vol_passed, vol_delta, vol_warnings = check_volume_confirmation(df)
    if not vol_passed:
        print(f"[signal] {display}: {vol_warnings[0]} -- skipping")
        return None
    confidence = max(0, min(100, confidence + vol_delta))
    conditions.extend(vol_warnings)

    # -- Momentum confirmation: +15 pts --
    trend      = analysis["market_structure"]["trend"]
    is_ranging = trend == "RANGING"
    mom_score, mom_reason = check_momentum(df, direction, is_ranging)
    confidence = min(100, confidence + mom_score)
    conditions.append(mom_reason)

    # -- HTF disagreement note --
    if not htf_agreement:
        conditions.append("HTF disagreement: confluence reduced by 2")

    # Calculate levels with swing-based stop loss
    current_price = analysis["key_levels"].get("current_price", float(df["close"].iloc[-1]))
    entry_low, entry_high, target, stop_loss, rr = calculate_entry_target_stop(
        analysis, direction, current_price, df
    )

    # -- Entry zone must be anchored to nearby structure --
    if not _validate_entry_near_structure(entry_low, entry_high, analysis):
        print(f"[signal] {display}: entry zone not anchored to structure -- skipping")
        return None

    # Reject poor R:R
    if rr < _MIN_RR:
        print(f"[signal] {display}: R:R {rr} < {_MIN_RR} -- skipping")
        return None

    # Build reasoning string
    pa_patterns = analysis["price_action"]["patterns"]
    vol_signal  = analysis["volume"]["signal"]

    parts = [f"{trend} trend", f"confluence {confluence}/6"]
    if pa_patterns:
        parts.append(f"PA: {', '.join(pa_patterns[:2])}")
    if vol_signal == "CONFIRMING":
        parts.append("volume confirming")
    elif vol_signal == "DIVERGING":
        parts.append("volume diverging")
    if not htf_agreement:
        parts.append("HTF disagreement")
    reasoning = " | ".join(parts)

    return Signal(
        asset=display,
        market=market,
        direction=direction,
        entry_low=entry_low,
        entry_high=entry_high,
        target=target,
        stop_loss=stop_loss,
        risk_reward=rr,
        confidence=confidence,
        confluence_score=confluence,
        conditions_met=conditions,
        reasoning=reasoning,
    )


# ── Market Scanner ────────────────────────────────────────────────────────────

def scan_all_markets(
    watchlist: Optional[Dict[str, List[str]]] = None,
) -> List[Signal]:
    """
    Scan every asset in the watchlist across all 4 markets and return valid
    signals sorted by confidence (descending).

    Args:
        watchlist: Optional override. Defaults to module-level WATCHLIST.

    Returns:
        List of Signal objects, sorted by confidence descending.
    """
    if watchlist is None:
        watchlist = WATCHLIST

    signals: List[Signal] = []
    total   = sum(len(v) for v in watchlist.values())
    scanned = 0

    for market, symbols in watchlist.items():
        for symbol in symbols:
            scanned += 1
            display = _DISPLAY_SYMBOL.get(symbol, symbol)
            print(f"[signal] Scanning {display:<10} ({market:<12}) [{scanned}/{total}]")
            sig = generate_signal(symbol, market)
            if sig:
                signals.append(sig)
                print(f"[signal]   + {sig.direction} signal  confidence {sig.confidence}%  R:R {sig.risk_reward}")
            else:
                print(f"[signal]   - no signal")

    signals.sort(key=lambda s: s.confidence, reverse=True)
    print(f"\n[signal] Scan complete. {len(signals)} signal(s) from {total} assets scanned.")
    return signals


# ── Module load confirmation ──────────────────────────────────────────────────
print(f"[signal_engine] Signal engine loaded — min_confluence={_MIN_CONFLUENCE}  min_rr={_MIN_RR}")


# ── Standalone test ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n" + "=" * 72)
    print("  AI Trading Agent -- Signal Engine Scan")
    print("=" * 72)

    signals = scan_all_markets()

    if not signals:
        print("\n  No qualifying signals found across all markets.")
    else:
        # Summary table
        print(f"\n  {'ASSET':<10} {'MKT':<12} {'DIR':<6} {'CONF':>5}  {'C/6':>4}"
              f"  {'ENTRY ZONE':<26}  {'TARGET':>12}  {'STOP':>12}  {'R:R':>5}")
        print(f"  {'-'*9} {'-'*11} {'-'*5} {'-'*5}  {'-'*4}"
              f"  {'-'*26}  {'-'*12}  {'-'*12}  {'-'*5}")

        for sig in signals:
            entry_zone = f"{sig.entry_low} - {sig.entry_high}"
            dir_arrow  = "^" if sig.direction == "LONG" else "v"
            print(
                f"  {sig.asset:<10} {sig.market:<12} {dir_arrow} {sig.direction:<4}"
                f" {sig.confidence:>4}%  {sig.confluence_score}/6"
                f"  {entry_zone:<26}  {sig.target:>12}  {sig.stop_loss:>12}"
                f"  {sig.risk_reward:>5}"
            )

        # Per-signal detail
        print(f"\n  {'=' * 72}")
        print("  SIGNAL DETAIL\n")
        for sig in signals:
            print(f"  +-- {sig.asset} ({sig.market})  {sig.direction}"
                  f"  confidence: {sig.confidence}%  R:R: {sig.risk_reward}")
            print(f"  |   Entry  : {sig.entry_low} -- {sig.entry_high}")
            print(f"  |   Target : {sig.target}")
            print(f"  |   Stop   : {sig.stop_loss}")
            print(f"  |   Bias   : {sig.reasoning}")
            for cond in sig.conditions_met:
                print(f"  |     * {cond}")
            print(f"  +-- {sig.timestamp}\n")

    print("=" * 72)
    print("  Test complete.")
    print("=" * 72 + "\n")
